version: '3.8'

services:
  api:
    #build: .
    image: registry.gitlab.com/vanessakovalibre/12-factors-app-python:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://userdb:password@db:5432/userdb
      - LOG_LEVEL=INFO
      - FLASK_ENV=development
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userdb -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: