version: '3'
name: js-microservice
services:
  appjs:
    build: .
    container_name: jsapp
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
  bdd:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: