version: '3.7'
services:
    registry:
        restart: always
        image: registry:2
        container_name: my-web-container
        volumes:
            - data/:/var/lib/registry/
            - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
            - ./auth/htpasswd:/etc/docker/registry/htpasswd
    ui:
        image: joxit/docker-registry-ui:static
        environment:
            REGISTRY_TITLE: "My Private Docker Registry"
            REGISTRY_URL: http://registry:5000
            NGINX_PROXY_HEADER_X_Forwarded_For: $$proxy_add_x_forwarded_for
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
          - ./nginx/privkey.pem:/etc/nginx/certs/privkey.pem
          - ./nginx/nginx.env:/etc/nginx/.env
        ports:
          - 8072:80
          - 443:443
        depends_on:
          - registry

volumes:
  data:
  nginx: