version: '3.7'
services:
    registry:
        restart: always
        image: registry:2
        container_name: my-web-container
        ports:
            - 5000:5000
        environment:
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/localhost.crt
            REGISTRY_HTTP_TLS_KEY: /certs/localhost.key
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - data/:/var/lib/registry/
            - ./certs/:/certs/
            - ./auth/:/auth/
volumes:
  certs: 
  auth:
  data: