version: '3.7'
services:
    registry:
        restart: always
        image: registry:2
        container_name: my-web-container
        volumes:
            - data/:/var/lib/registry/
    ui:
        image: joxit/docker-registry-ui:static
        environment:
            REGISTRY_TITLE: "My Private Docker Registry"
            REGISTRY_URL: http://registry:5000
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
          - ./nginx/privkey.pem:/etc/nginx/certs/privkey.pem
        ports:
          - 8072:80
          - 443:443
        depends_on:
          - registry

volumes:
  data:
  nginx: