version: '3.8'

services:
  app:
    restart: unless-stopped
    # Retirer les ports pour utiliser Traefik
    ports: []
    
    environment:
      - DEBUG=false
      - LOG_LEVEL=warn
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-prod.rule=Host(`myapp.example.com`)"
      - "traefik.http.routers.app-prod.tls.certresolver=letsencrypt"
    # Ne pas exposer les volumes en production
    volumes: []

  postgres:
    restart: unless-stopped
    # Ne pas exposer le port en production
    ports: []
    environment:
      - POSTGRES_LOG_STATEMENT=none
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      # Pas de script d'init en production

  # Retirer pgadmin en production
  pgadmin:
    image: dpage/pgadmin4:latest
    deploy:
      replicas: 0

volumes:
  postgres_prod_data: