apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nginx
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: DEBUG
          value: "False"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:   
              name: db-secret
              key: password